CREATE DATABASE bdEtecqlqr
USE bdEtecqlqr
GO

CREATE TABLE tb2A(
	rm INT PRIMARY KEY
	,nomeAluno VARCHAR(50) NOT NULL
	,statusAluno VARCHAR(9) NOT NULL
)

CREATE TABLE tb2B(
	rm INT PRIMARY KEY
	,nomeAluno VARCHAR(50) NOT NULL
	,statusAluno VARCHAR(9) NOT NULL
)